2021-07-27 11:20:41,118 [INFO] host = localhost, port = 29500
2021-07-27 11:20:43,122 [INFO] sending message $BPLOG,ACK,ON*1e
...
2021-07-27 11:20:43,122 [INFO] sending message $BPLOG,ALL,ON*16
...
2021-07-27 11:20:43,122 [INFO] sending message $BPSTS,152043.12,1,BWSI Autonomy OK*46
...
2021-07-27 11:20:43,122 [INFO] Received from Frontseat: []
2021-07-27 11:20:43,122 [INFO] AUV state: {'position': (None, None), 'latlon': None, 'heading': None, 'depth': None, 'altitude': None, 'roll': None, 'pitch': None, 'last_fix_time': None, 'speed': None, 'rudder': 0}
2021-07-27 11:20:43,122 [ERROR] An error occurred. The stack trace is below.
Traceback (most recent call last):
  File "BWSI_BackSeat.py", line 110, in run
    green, red = self.__buoy_detector.run(self.__auv_state)
  File "/home/steven/Baygulls/ChallengeCode/Image_Processor.py", line 177, in run
    cv2.imwrite(str(fn), image)
UnboundLocalError: local variable 'image' referenced before assignment
